#!/bin/bash
export DOCKER_HOST="${DOCKER_HOST_ORIGINAL}"
export DOCKER_TLS_VERIFY="${DOCKER_TLS_VERIFY_ORIGINAL}"
export DOCKER_CERT_PATH="${DOCKER_CERT_PATH_ORIGINAL}"
export DOCKER_NATIVE="${DOCKER_NATIVE_ORIGINAL}"
export KUBERNETES_MASTER="${KUBERNETES_MASTER_ORIGINAL}"
